# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("530x530")
window.configure(bg="#FFFFFF")


canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=530,
    width=530,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(265.0, 265.0, image=image_image_1)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(115.0, 74.0, image=image_image_2)

canvas.create_rectangle(49.0, 157.0, 489.0, 220.0, fill="#B4D9FA", outline="")

entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(445.5, 172.0, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_1.place(x=411.0, y=163.0, width=69.0, height=16.0)

canvas.create_rectangle(49.0, 257.0, 489.0, 361.0, fill="#A8B6FF", outline="")

entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(315.5, 325.0, image=entry_image_2)
entry_2 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_2.place(x=162.0, y=303.0, width=307.0, height=42.0)

canvas.create_rectangle(49.0, 396.0, 489.0, 473.0, fill="#869AFF", outline="")

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
)
button_1.place(x=56.0, y=438.0, width=90.0, height=23.0)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
)
button_2.place(x=59.0, y=273.0, width=90.0, height=23.0)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
)
button_3.place(x=59.0, y=166.0, width=90.0, height=23.0)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
)
button_4.place(x=56.0, y=412.0, width=90.0, height=23.0)

canvas.create_rectangle(52.0, 145.0, 497.0, 155.0, fill="#174AFF", outline="")

canvas.create_rectangle(385.0, 127.0, 497.0, 150.0, fill="#174AFF", outline="")

canvas.create_rectangle(51.0, 384.0, 496.0, 394.0, fill="#0C2DA0", outline="")

canvas.create_rectangle(281.0, 368.0, 496.0, 389.0, fill="#0C2DA0", outline="")

canvas.create_rectangle(51.0, 245.0, 496.0, 255.0, fill="#133FDB", outline="")

canvas.create_rectangle(332.0, 229.0, 496.0, 250.0, fill="#133FDB", outline="")

canvas.create_text(
    397.0,
    131.0,
    anchor="nw",
    text="TED & Similarity",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1),
)

canvas.create_text(
    427.0,
    233.0,
    anchor="nw",
    text="Edit Script",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1),
)

canvas.create_text(
    436.0,
    373.0,
    anchor="nw",
    text="Patching",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1),
)

entry_image_3 = PhotoImage(file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(236.5, 176.0, image=entry_image_3)
entry_3 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_3.place(x=162.0, y=166.0, width=149.0, height=18.0)

entry_image_4 = PhotoImage(file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(247.0, 283.0, image=entry_image_4)
entry_4 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_4.place(x=162.0, y=273.0, width=170.0, height=18.0)

entry_image_5 = PhotoImage(file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(247.0, 422.0, image=entry_image_5)
entry_5 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_5.place(x=162.0, y=412.0, width=170.0, height=18.0)

entry_image_6 = PhotoImage(file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(247.0, 449.0, image=entry_image_6)
entry_6 = Entry(bd=0, bg="#FFF9F9", highlightthickness=0)
entry_6.place(x=162.0, y=439.0, width=170.0, height=18.0)

entry_image_7 = PhotoImage(file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(236.5, 200.0, image=entry_image_7)
entry_7 = Entry(bd=0, bg="#FFFFFF", highlightthickness=0)
entry_7.place(x=162.0, y=191.0, width=149.0, height=16.0)

button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
)
button_5.place(x=49.0, y=491.0, width=78.0, height=26.0)
window.resizable(False, False)
window.mainloop()
