
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def previousPage():
    window.destroy()
    import page2

window = Tk()

window.geometry("763x528")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 528,
    width = 763,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    381.0,
    264.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    130.0,
    62.0,
    image=image_image_2
)

canvas.create_rectangle(
    116.0,
    145.0,
    639.0,
    208.0,
    fill="#B4D9FA",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    564.5,
    164.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_1.place(
    x=515.0,
    y=154.0,
    width=99.0,
    height=18.0
)

canvas.create_rectangle(
    116.0,
    245.0,
    639.0,
    356.0,
    fill="#A8B6FF",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    488.0,
    302.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_2.place(
    x=355.0,
    y=259.0,
    width=266.0,
    height=85.0
)

canvas.create_rectangle(
    116.0,
    392.0,
    639.0,
    469.0,
    fill="#869AFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=124.3125,
    y=434.0,
    width=106.875,
    height=23.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=128.0,
    y=252.0,
    width=106.875,
    height=23.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=130.0,
    y=300.0,
    width=103.0,
    height=23.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=127.875,
    y=154.0,
    width=106.875,
    height=23.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=124.3125,
    y=408.0,
    width=106.875,
    height=23.0
)

canvas.create_rectangle(
    120.0,
    133.0,
    648.0,
    143.0,
    fill="#174AFF",
    outline="")

canvas.create_rectangle(
    515.0,
    115.0,
    648.0,
    138.0,
    fill="#174AFF",
    outline="")

canvas.create_rectangle(
    118.0,
    380.0,
    647.0,
    390.0,
    fill="#0C2DA0",
    outline="")

canvas.create_rectangle(
    392.0,
    364.0,
    647.0,
    385.0,
    fill="#0C2DA0",
    outline="")

canvas.create_rectangle(
    118.0,
    233.0,
    647.0,
    243.0,
    fill="#133FDB",
    outline="")

canvas.create_rectangle(
    452.0,
    217.0,
    647.0,
    238.0,
    fill="#133FDB",
    outline="")

canvas.create_text(
    529.0,
    119.0,
    anchor="nw",
    text="TED & Similarity",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1)
)

canvas.create_text(
    565.0,
    221.0,
    anchor="nw",
    text="Edit Script",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1)
)

canvas.create_text(
    576.0,
    369.0,
    anchor="nw",
    text="Patching",
    fill="#FFFFFF",
    font=("Arial BoldMT", 12 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    338.5,
    164.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_3.place(
    x=250.0,
    y=154.0,
    width=177.0,
    height=18.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    238.0,
    287.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_4.place(
    x=137.0,
    y=277.0,
    width=202.0,
    height=18.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    238.0,
    336.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_5.place(
    x=137.0,
    y=326.0,
    width=202.0,
    height=18.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    351.0,
    418.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_6.place(
    x=250.0,
    y=408.0,
    width=202.0,
    height=18.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    351.0,
    445.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFF9F9",
    highlightthickness=0
)
entry_7.place(
    x=250.0,
    y=435.0,
    width=202.0,
    height=18.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    338.5,
    188.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_8.place(
    x=250.0,
    y=179.0,
    width=177.0,
    height=16.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=previousPage,
    relief="flat"
)
button_6.place(
    x=328.0,
    y=484.0,
    width=78.0,
    height=26.0
)

canvas.create_rectangle(
    614.0,
    153.0,
    621.0,
    174.0,
    fill="#869AFF",
    outline="")

canvas.create_text(
    615.0,
    165.0,
    anchor="nw",
    text="v",
    fill="#0C2DA0",
    font=("Arial BoldMT", 9 * -1)
)
window.resizable(False, False)
window.mainloop()
